version: '3'
services:
#mssql docker
  treatbeauty-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - TreatBeautynet

  treatbeauty-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=treatbeauty-sql,1433;Database=TreatBeauty;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5001:5001
    networks:
      - TreatBeautynet      
    links:
      - treatbeauty-sql
    depends_on:
      - treatbeauty-sql
      
networks:
  TreatBeautynet:
    driver: bridge 